### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by dinpor** [llychao/m3u8-downloader#1]
### 运行报错了，使用完整命令和精简命令都不行，希望能作者能解决，谢谢了。
>unhappy@wyxwyx Downloads % ./m3u8-darwin-amd64 -u=https://upyuncache.gensee.com/gsgetrecord/record51.gensee.net/gsrecord/2932/sbr/2020_09_16/c867a9958f1d4ff2a2a7a2425d8b9214_1600255962/hls/record.m3u8
[功能]:多线程下载直播流m3u8的视屏（ts+合并）
[提醒]:如果下载失败，请使用-ht=apiv2
[提醒]:如果下载失败，m3u8地址可能存在嵌套
[提醒]:如果进度条中途下载失败，可重复执行
待下载ts文件数量: 0
panic: exit status 1

>goroutine 1 [running]:
main.ExecUnixShell(0x132ae7c, 0x15)
	/Users/chao/go/lyc/tool/m3u8-downloader.go:304 +0x225
main.unix_merge_file(0xc00008e030, 0x25)
	/Users/chao/go/lyc/tool/m3u8-downloader.go:334 +0x52
main.Run()
	/Users/chao/go/lyc/tool/m3u8-downloader.go:114 +0x496
main.main()
	/Users/chao/go/lyc/tool/m3u8-downloader.go:63 +0x20

**Comment by llychao** [comment]
可以下载的呀，如下：
![image](https://user-images.githubusercontent.com/69511585/99755768-90060f80-2b26-11eb-8c65-0bfd9603769d.png)

**Comment by llychao** [comment]
我帮你下载了上传到百度云：可自取
链接: https://pan.baidu.com/s/1ZwBM9glrq2L-604d_eRn3A 提取码: 6666 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by brownchow** [comment]
![image](https://user-images.githubusercontent.com/8622915/110961979-5eda7500-838b-11eb-9772-f5d46f075f45.png)
我这边也可以的
