### ISSUE TITLE
Bug when merging 1080p vs. 720p

### ISSUE THREAD

**Issue by articice** [llychao/m3u8-downloader#12]
Weird bug skipping some portions of the video at merge boundary, try to compare
./m3u8-linux-amd64 -u https://d1lf3486063qdz.cloudfront.net/category-reels/house/house-1080p.m3u8
and
./m3u8-linux-amd64 -u https://d1lf3486063qdz.cloudfront.net/category-reels/house/house-720p.m3u8

there are 2 types of errors produced by mplayer:
```
[h264 @ 0x7f5aa3e044c0]Invalid NAL unit 6, skipping.
[h264 @ 0x7f5aa3e044c0]error while decoding MB 52 26, bytestream -7
[h264 @ 0x7f5aa3e044c0]concealing 5037 DC, 5037 AC, 5037 MV errors in P frame
```

```
[aac @ 0x7f5aa3e044c0]Got unexpected packet after EOF
[aac @ 0x7f5aa3e044c0]invalid band type
[aac @ 0x7f5aa3e044c0]Prediction is not allowed in AAC-LC.
```

**Comment by Junyi-99** [comment]
This is because a bug in the code.

The bug is described in #16, that sometimes there are some .ts files missing.

and the fixed version is pending to merge. However, you can try to use [my version](https://github.com/Junyi-99/m3u8-downloader)

**Comment by llychao** [comment]
已经发布 v1.4版本，欢迎下载使用
