### ISSUE TITLE
下载后的文件去哪了？

### ISSUE THREAD

**Issue by bthulu** [llychao/m3u8-downloader#14]
看起来下好了， 但是合并后的文件去哪里了？m3u8-windows-amd64.exe所在目录下没有，windows视频文件夹下也没有

[功能]:多线程下载直播流m3u8的视屏（ts+合并）
[提醒]:如果下载失败，请使用-ht=apiv2
[提醒]:如果下载失败，m3u8地址可能存在嵌套
[提醒]:如果进度条中途下载失败，可重复执行
待下载ts文件数量: 26
2021/08/02 20:53:52 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000006.ts, Retry %!s(int=-1)
[Downloading] ■                                          3.85%         00007.ts2021/08/02 20:53:52 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000014.ts, Retry %!s(int=-1)
[Downloading] ■■■                                        7.69%       00015.ts2021/08/02 20:53:52 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000009.ts, Retry %!s(int=-1)
[Downloading] ■■■■                                      11.54%      00010.ts2021/08/02 20:53:52 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000007.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■                                    15.38%    00008.ts2021/08/02 20:53:52 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000015.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■                                   19.23%   00016.ts2021/08/02 20:53:52 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000011.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■                                 23.08%         00012.ts2021/08/02 20:53:52 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000003.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■                                26.92%        00004.ts2021/08/02 20:53:52 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000000.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■■■                              30.77%      00001.ts2021/08/02 20:53:52 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000001.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■■■■                             34.62%     00002.ts2021/08/02 20:53:52 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000008.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■■■■■■                           38.46%   00009.ts2021/08/02 20:53:52 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000002.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■■■■■■■                          42.31%  00003.ts2021/08/02 20:53:52 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000004.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■■■■■■■■■                        46.15%        00005.ts2021/08/02 20:53:52 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000010.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■■■■■■■■■■■                      50.00%      00011.ts2021/08/02 20:53:52 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000013.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■■■■■■■■■■■■                     53.85%     00014.ts2021/08/02 20:53:52 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000012.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■■■■■■■■■■■■■■                   57.69%   00013.ts2021/08/02 20:53:52 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000005.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■■■■■■■■■■■■■■■                  61.54%  00006.ts2021/08/02 20:53:56 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000016.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■■■■■■■■■■■■■■■■■                65.38%        00017.ts2021/08/02 20:53:56 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000020.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■■■■■■■■■■■■■■■■■■               69.23%       00021.ts2021/08/02 20:53:56 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000017.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■             73.08%     00018.ts2021/08/02 20:53:56 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000018.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■            76.92%    00019.ts2021/08/02 20:53:56 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000025.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■          80.77%  00026.ts2021/08/02 20:53:56 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000022.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■         84.62%         00023.ts2021/08/02 20:53:56 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000019.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■       88.46%       00020.ts2021/08/02 20:53:56 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000021.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■      92.31%      00022.ts2021/08/02 20:53:56 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000023.ts, Retry %!s(int=-1)
[Downloading] ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■    96.15%    00024.ts2021/08/02 20:53:56 m3u8-downloader.go:237: [warn] File :https://a01-g-naver-vod.pstatic.net/blog/a/read/v2/VOD_ALPHA/blog_2021_07_05_1827/hls/bb4eea4e-dd2d-11eb-ba8f-9aead4722fa8-000024.ts, Retry %!s(int=-1)
[Merging] ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 100.00%      merge.ts
Done! 耗时: 10.15s

**Comment by yuedingwangji** [comment]
你这就是下载失败的意思，所以就没有文件，默认文件夹是output

**Comment by Junyi-99** [comment]
看一下你的 cmd 窗口

**Comment by llychao** [comment]
已经发布了v1.4版本，增加了自定义保存路径，欢迎大家下载了尝试。
