### ISSUE TITLE
CentOS7下使用报错，无法下载，无论是完整模式还是精简模式

### ISSUE THREAD

**Issue by gimgoo** [llychao/m3u8-downloader#15]
如题，下载报错，
`goroutine 1 [running]:
main.ExecUnixShell(0x729a23, 0x15)
	/Users/chao/go/lyc/tool/m3u8-downloader.go:311 +0x225
main.unix_merge_file(0xc000016160, 0x17)
	/Users/chao/go/lyc/tool/m3u8-downloader.go:341 +0x52
main.Run()
	/Users/chao/go/lyc/tool/m3u8-downloader.go:121 +0x4ab
main.main()
	/Users/chao/go/lyc/tool/m3u8-downloader.go:64 +0x20`

**Comment by llychao** [comment]
已经发布了 v1.4版本。欢迎大家下载尝试
