### ISSUE TITLE
下载片段不完整，有时会解密报错

### ISSUE THREAD

**Issue by Junyi-99** [llychao/m3u8-downloader#16]
发现下载视频，merge之后，部分片段丢失（表现为视频跳帧）
随后发现：
panic: crypto/cipher: input not full blocks

（正在尝试修复

**Comment by Junyi-99** [comment]
panic: runtime error: index out of range [-1]

goroutine 51 [running]:
main.PKCS7UnPadding(...)
	/.../m3u8-downloader/m3u8-downloader.go:370
main.AesDecrypt(0x0, 0x0, 0x0, 0xc00001d860, 0x10, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
	/.../m3u8-downloader/m3u8-downloader.go:408 +0x205
main.downloadTsFile(0xc00009ea30, 0x8, 0xc0000aae40, 0xbd, 0xc000024120, 0x57, 0xc00009e990, 0x10, 0x5)
	/.../m3u8-downloader/m3u8-downloader.go:262 +0x2f1
main.downloader.func1(0xc00009edb0, 0xc0000a8600, 0xc00009edc0, 0x82, 0xc00009ea30, 0x8

**Comment by Junyi-99** [comment]
```go
func PKCS7UnPadding(origData []byte) []byte {
	length := len(origData)
        // 这里 length ==0 出现的错误
	unpadding := int(origData[length-1])
	return origData[:(length - unpadding)]
}
```

**Comment by Junyi-99** [comment]
有些文件下载成这样：
<img width="635" alt="image" src="https://user-images.githubusercontent.com/14367694/140951368-3ce6a968-c3cc-4c81-97ad-11f6bb5716a1.png">

**Comment by Junyi-99** [comment]
原因是因为网速过慢导致 reach 到 timeout, 本应该返回 1796160 字节却只返回了 188132 字节。导致 AES 解码失败。

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/14367694/140955160-d44e2c39-f1c7-4096-8350-0828a8846ecd.png">

**Comment by Junyi-99** [comment]
```go
res, err := grequests.Get(ts.Url, ro)
        // 这里的判断逻辑应该加上 !res.Error.timeout
	if err != nil || !res.Ok {
```

**Comment by Junyi-99** [comment]
### 复现方法：
```go
HEAD_TIMEOUT = 0.5 * time.Second
```

**Comment by llychao** [comment]
已经发布了v1.4版本，欢迎大家下载了尝试。
