### ISSUE TITLE
Mac m1 下使用，最后merge的时候报错

### ISSUE THREAD

**Issue by a1324321** [llychao/m3u8-downloader#18]
如下图

**Comment by a1324321** [comment]
![WX20211115-110113](https://user-images.githubusercontent.com/5265881/141715829-376e077c-e1e1-4102-b0ed-61d1305061a4.png)

**Comment by llychao** [comment]
升级到 v1.4版本了，直接下载编译好的文件试试。我的也是 Mac-m1 ，没看到报错

**Comment by Fu1haha** [comment]
我升级到1.4了 还是报错 跟楼主一样

**Comment by llychao** [comment]
> ![WX20211115-110113](https://user-images.githubusercontent.com/5265881/141715829-376e077c-e1e1-4102-b0ed-61d1305061a4.png)

升级到 v1.6版本了
