### ISSUE TITLE
当m3u8包含多个分辨率的ts流时，程序没有正确下载，只下载了一个m3u8文件

### ISSUE THREAD

**Issue by karma-sun** [llychao/m3u8-downloader#20]
当m3u8包含多个分辨率的ts流时，程序没有正确下载，只下载了一个m3u8

**Comment by llychao** [comment]
> 当m3u8包含多个分辨率的ts流时，程序没有正确下载，只下载了一个m3u8

暂时不支持嵌套m3u8,建议获取单个m3u8再使用
