### ISSUE TITLE
您好，我是小白请问mac系统下怎么使用？

### ISSUE THREAD

**Issue by black373707314** [llychao/m3u8-downloader#21]
如题，非常感谢解答

**Comment by llychao** [comment]
> 如题，非常感谢解答

1、先下载：https://github.com/llychao/m3u8-downloader/releases/download/v1.4/m3u8-darwin-amd64
2、然后找到下载的文件：m3u8-darwin-amd64，
3、打开命令行工具：cd 到文件m3u8-darwin-amd64 所在目录
4、执行命令  ：./m3u8-darwin-amd64. -u="你需要下载的 m3u8 url"
5、泡壶茶，小憩一杯
6、不出意外，下载完了！

**Comment by black373707314** [comment]
非常感谢您的解答
