### ISSUE TITLE
v1.6 下载结束后产生的临时目录不会被删除,指定下载目录后,路径后面会被自动补上movie这文件夹

### ISSUE THREAD

**Issue by Manx98** [llychao/m3u8-downloader#22]
下面是v1.6在Win10 x64 运行结果。
![bug](https://user-images.githubusercontent.com/39939386/148565262-d0adb13c-ffce-421f-9c26-071c2b9f88ba.gif)

**Comment by Manx98** [comment]
我后面尝试自己修复了一下：https://github.com/Manx98/m3u8-downloader.git，目前是能够正常使用了，也不知道改得对不对。

**Comment by llychao** [comment]
> 下面是v1.6在Win10 x64 运行结果。 ![bug](https://user-images.githubusercontent.com/39939386/148565262-d0adb13c-ffce-421f-9c26-071c2b9f88ba.gif)

2.0版本 修复啦。
