### ISSUE TITLE
v2.0存在路径问题

### ISSUE THREAD

**Issue by n0thing2speak** [llychao/m3u8-downloader#23]
使用版本：mac
错误：所有ts片段下载完成后出现如下报错
```
panic: exit status 1

goroutine 1 [running]:
main.ExecUnixShell({0x12941bd, 0xc0003eb380})
	/Users/liyuchao/m3u8-downloader/m3u8-downloader.go:319 +0x165
main.unix_merge_file({0xc000128060, 0x9d})
	/Users/liyuchao/m3u8-downloader/m3u8-downloader.go:349 +0x2f
main.Run()
	/Users/liyuchao/m3u8-downloader/m3u8-downloader.go:125 +0x59b
main.main()
	/Users/liyuchao/m3u8-downloader/m3u8-downloader.go:69 +0x17
```

**Comment by llychao** [comment]
> 使用版本：mac 错误：所有ts片段下载完成后出现如下报错
> 
> ```
> panic: exit status 1
> 
> goroutine 1 [running]:
> main.ExecUnixShell({0x12941bd, 0xc0003eb380})
> 	/Users/liyuchao/m3u8-downloader/m3u8-downloader.go:319 +0x165
> main.unix_merge_file({0xc000128060, 0x9d})
> 	/Users/liyuchao/m3u8-downloader/m3u8-downloader.go:349 +0x2f
> main.Run()
> 	/Users/liyuchao/m3u8-downloader/m3u8-downloader.go:125 +0x59b
> main.main()
> 	/Users/liyuchao/m3u8-downloader/m3u8-downloader.go:69 +0x17
> ```

应该是 ts 视频片段下载失败了（m3u8鉴权原因）。
