### ISSUE TITLE
可不可以加一个可以自定义key的功能

### ISSUE THREAD

**Issue by wuabuhuan** [llychao/m3u8-downloader#39]
可不可以加一个可以自定义key的功能，用户可以自行输入Base64字符串解密，以防止在另一台机器拉取视频的时候访问受限

**Comment by llychao** [comment]
> 可不可以加一个可以自定义key的功能，用户可以自行输入Base64字符串解密，以防止在另一台机器拉取视频的时候访问受限

自定义key的功能是为了解密 ts 视频片段! 
访问受限有两种情况：
1、权限校验，一般是 cookie 等引起，使用 `-c` 参数携带 cookie 信息。
2、https 安全证书校验，使用`-s`参数开启安全证书校验
