### ISSUE TITLE
编译时出现以下问题

### ISSUE THREAD

**Issue by vjsdhyygy** [llychao/m3u8-downloader#4]
````
 go build  -o ./Releases/m3u8-linux-mipsel m3u8-downloader.go
m3u8-downloader.go:12:2: cannot find module providing package github.com/levigross/grequests: working directory is not part of a module
````

平台 linux / mipsle 
直接在我的路由器中编译的  
已经
`go get github.com/levigross/grequests`

````
[RT-N56U_B1 /opt/home/admin/m3u8-downloader]# go version
go version go1.15.5 linux/mipsle
````

**Comment by llychao** [comment]
> ```
>  go build  -o ./Releases/m3u8-linux-mipsel m3u8-downloader.go
> m3u8-downloader.go:12:2: cannot find module providing package github.com/levigross/grequests: working directory is not part of a module
> ```
> 
> 平台 linux / mipsle
> 直接在我的路由器中编译的
> 已经
> `go get github.com/levigross/grequests`
> 
> ```
> [RT-N56U_B1 /opt/home/admin/m3u8-downloader]# go version
> go version go1.15.5 linux/mipsle
> ```

提示没找到这个包，检查一下GOPATH

**Comment by llychao** [comment]
已经发布了 v1.4版本，增加了 gomod 管理依赖。欢迎大家下载尝试
