### ISSUE TITLE
提点建议

### ISSUE THREAD

**Issue by Kiritomo** [llychao/m3u8-downloader#6]
1.虽然目前可以自定义文件名，但是不支持自定义路径，合并的时候默认也是转换成mp4，建议检测-o参数里面是否包含路径和文件扩展名以达到自定义的目的。
2.上次提了某些需要cookie才能获取到密钥，但是有些是需要伪造请求头的，不止有cookie还有其他的，建议还是把那个-c的参数改成请求头的。

**Comment by CaiNiaoHui** [comment]
已经增加了自定义路径的功能.

**Comment by llychao** [comment]
已经发布了v1.4版本，已经增加了自定义路径，欢迎大家下载了尝试。
