### ISSUE TITLE
播放卡顿跳跃是ts下载有问题，有的ts下载下来文件大小根本没有res.Header["Content-Length"]那么大，需要校验

### ISSUE THREAD

**Issue by yqxyz** [llychao/m3u8-downloader#7]
我自己把下面代码去掉用ffmpeg和并，不校验可能合并一些就停止了，校验后就不会出问题了
`syncByte := uint8(71) //0x47
	bLen := len(origData)
	for j := 0; j < bLen; j++ {
		if origData[j] == syncByte {
			origData = origData[j:]
			break
		}
	}`

**Comment by yqxyz** [comment]
> 我自己把下面代码去掉用ffmpeg和并，不校验可能合并一些就停止了，校验后就不会出问题了
> `syncByte := uint8(71) //0x47 bLen := len(origData) for j := 0; j < bLen; j++ { if origData[j] == syncByte { origData = origData[j:] break } }`

也可能是这段代码造成的，不过下载确实是可能会出问题

**Comment by DuoFuShun** [comment]
是的，部分影片，直接中间卡住然后跳帧等，不是原影片那么顺滑，希望大佬研究研究为什么

**Comment by loskael** [comment]
+ 数据的完整性确实有问题，同一个视频资源多次下载，生成的文件大小不同
+ 合并之后的文件并不是 MP4 格式，应该还是 TS 格式
+ 另外，使用 ffmpeg 将 TS 文件转成 MP4 遇到如下错误（使用 VLC 转换也会中断）
```
[AVBSFContext @ 0x55b1f6189580] Error parsing ADTS frame header!
[AVBSFContext @ 0x55b1f6189580] Failed to send packet to filter aac_adtstoasc for stream 0
av_interleaved_write_frame(): Invalid data found when processing input
```

**Comment by Junyi-99** [comment]
这个问题已经修复 #17 ，正在等待作者 merge
Issue #16
